services:
  api:
    container_name: $API__SERVER_HOST
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - postgres
    ports:
      - $API__SERVER_PORT:5000
    command: bash -c "./scripts/wait-for-it.sh $POSTGRES__HOST:5432 -- \
          && alembic upgrade head \
          && export PYTHONPATH=/app \
          && uvicorn src.main:app --host 0.0.0.0 --port $API__SERVER_PORT --reload"
    networks:
      - wallet

  postgres:
    container_name: $POSTGRES__HOST
    build:
      context: .
      dockerfile: docker/postgresql/Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=$POSTGRES__PASSWORD
      - POSTGRES_USER=$POSTGRES__USER
      - POSTGRES_DB="$POSTGRES__DATABASE_NAME"
    ports:
      - $POSTGRES__PORT:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - wallet

networks:
  wallet:
      name: wallet_network
